add access control to service level
OceanProtocolEnterprise/ocean-node pull request #12
Opened 2024-03-24 19:42 UTC by FilipMasar

Fixes #7 

## Changes proposed in this PR:
- add credentials field in Service
- check service credentials in download task

## Open questions?
- do we need to check these credentials also somewhere else?
- should we write some tests?
- once this is released, there might be an issue with old providers which are not checking this new credentials field and therefor allow downloading dataset even though it should be denied. Is there some mechanism how we can prevent this?

2024-04-02 15:30 UTC, alexcos20 requested changes
Can you add some tests as well ?

2024-04-19 15:38 UTC, FilipMasar commented
@alexcos20 tests are done. Please have a look. I updated the PR description.

2024-05-21 07:14 UTC, alexcos20 approved these changes

2024-05-21 07:14 UTC, alexcos20 approved these changes

2024-05-21 09:55 UTC, merged